tls:
  active: false
  crt: server.crt
  key: server.key

basicAuth:
  active: false
  username: admin
  password: admin

bearerAuth:
  active: false
  signingKey: my_secret_key

timeouts:
  max_timeout: 0

scripts:
  - name: test
    script: ./examples/test.sh
  - name: ping
    script: ./examples/ping.sh
  - name: helloworld
    script: ./examples/helloworld.sh test
  - name: curltest
    script: ./bin/curltest
  - name: showtimeout
    script: ./examples/showtimeout.sh
    timeout:
      max_timeout: 60
