tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: admin
  password: admin

bearerAuth:
  enabled: false
  signingKey: my_secret_key

discovery:
  # host: localhost
  # port: 1231
  # scheme: https

scripts:
  - name: test
    script: sh /bin/examples/test.sh
  - name: ping
    script: sh /bin/examples/ping.sh
  - name: helloworld
    script: sh /bin/examples/helloworld.sh test
  - name: showtimeout
    script: sh /bin/examples/showtimeout.sh
    timeout:
      max_timeout: 60
  - name: sleep
    script: sleep 120
    timeout:
      enforced: true
  - name: docker
    script: sh /bin/examples/docker.sh
  - name: args
    script: sh /bin/examples/args.sh test1 test2
