tls:
  enabled: false
  crt: server.crt
  key: server.key

basicAuth:
  enabled: false
  username: admin
  password: admin

bearerAuth:
  enabled: false
  signingKey: my_secret_key

scripts:
  - name: test
    script: ./examples/test.sh
  - name: ping
    script: ./examples/ping.sh
  - name: helloworld
    script: ./examples/helloworld.sh test
  - name: showtimeout
    script: ./examples/showtimeout.sh
    timeout:
      max_timeout: 60
  - name: sleep
    script: sleep 120
    timeout:
      enforced: true
