---
apiVersion: v1
kind: Namespace
metadata:
  name: script-exporter

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: script-exporter
  namespace: script-exporter
  labels:
    app.kubernetes.io/name: script-exporter
data:
  config.yaml: |
    tls:
      enabled: false

    basicAuth:
      enabled: false

    bearerAuth:
      enabled: false

    scripts:
      - name: test
        script: sh /etc/script_exporter/test.sh

  test.sh: |
    #! /bin/bash

    echo "# HELP test_first_test"
    echo "# TYPE test_first_test gauge"
    echo "first_test{label=\"test_1_label_1\"} 1"
    echo ""
    echo "# HELP test_second_test"
    echo "# TYPE test_second_test gauge"
    echo "second_test{label=\"test_2_label_1\",label=\"test_2_label_2\"} 2.71828182846"
    echo ""
    echo "# HELP test_third_test"
    echo "# TYPE test_third_test gauge"
    echo "third_test{} 3,14159265359"
    echo ""
    echo "Fourth test"
    echo "fourth label=\"test_1_label_1\ 4"
    echo ""
    echo "Fifth test"
    echo "fifth 5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-exporter
  namespace: script-exporter
  labels:
    app.kubernetes.io/name: script-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: script-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: script-exporter
    spec:
      containers:
        - name: script-exporter
          image: ricoberger/script_exporter:v2.1.1
          args:
            - -config.file=/etc/script_exporter/config.yaml
          ports:
            - name: http
              containerPort: 9469
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9469
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 9469
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - name: config
              mountPath: /etc/script_exporter
      volumes:
        - name: config
          configMap:
            name: script-exporter
            defaultMode: 0777
